package c98.core.impl.asm;

import java.util.ArrayList;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiScreen;
import net.minecraft.client.renderer.Tessellator;
import net.minecraftforge.fml.client.*;
import net.minecraftforge.fml.common.*;
import org.lwjgl.Sys;
import c98.core.C98Core;
import c98.core.XCube;
import c98.core.launch.ASMer;

@ASMer class ForgeModMenu extends GuiModList {
	public static class ForgeStatic {
		public static XCube xCube = new XCube();
		public static ModContainer c98ModContainer;
		static {
			ModMetadata meta = new ModMetadata();
			meta.modId = "C98Mods";
			meta.name = "C98Mods";
			meta.version = "1.10"; // TODO don't hardcode
			meta.autogenerated = true;
			c98ModContainer = new DummyModContainer(meta);
		}
	}

	@ASMer static class ClientHandler extends FMLClientHandler {
		@Override public void addSpecialModEntries(ArrayList<ModContainer> mods) {
			mods.add(ForgeStatic.c98ModContainer);
			super.addSpecialModEntries(mods);
		}
	}

	@ASMer static class ForgeModMenuList extends GuiSlotModList {
		public ForgeModMenuList(GuiModList parent, ArrayList<ModContainer> mods, int listWidth, int slotHeight) {
			super(parent, mods, listWidth, slotHeight);
		}

		@Override public void drawSlot(int idx, int right, int top, int height, Tessellator tess) {
			ModContainer mod = mods.get(idx);
			if(mod == ForgeStatic.c98ModContainer) {
				int x = left + 3;
				int y = top + 2;
				Minecraft.getMinecraft().fontRendererObj.drawString(mod.getName(), x + 28, y + 10, 0xFFFFFF);
				ForgeStatic.xCube.drawImage(x + 4, y + 1);
			} else super.drawSlot(idx, right, top, height, tess);
		}
	}

	public ForgeModMenu(GuiScreen m) {
		super(m);
	}

	@Override public void initGui() {
		listWidth = Math.max(listWidth, fontRendererObj.getStringWidth(ForgeStatic.c98ModContainer.getName()) + 28);
		super.initGui();
	}

	@Override public void selectModIndex(int index) {
		if(mods.get(index) == ForgeStatic.c98ModContainer) Sys.openURL(C98Core.URL);
		else super.selectModIndex(index);
	}

	@Override public void drawScreen(int mouseX, int mouseY, float partialTicks) {
		super.drawScreen(mouseX, mouseY, partialTicks);
		ForgeStatic.xCube.tooltip();
	}
}
